名称：名称：使用 Conda 的 Python 包

: [上：[推]  ]

工作：
  构建Linux：
    running-on :     运行：ubuntu-latest
    战略：
      最大并行数：5

    脚步：
    -使用:      - 使用：actions/checkout@v3
    - name :      - 名称：设置Python 3.10
      使用：       使用：actions/setup-python@v3
      和：
        python-版本：'3.10'
    - name :      - name :将 conda 添加到系统路径
      运行：|
        # $CONDA 是一个环境变量，指向 miniconda 目录的根目录
        回声 $CONDA/bin >> $GITHUB_PATH
    - name :      - 名称：安装依赖项
      运行：|
        conda env update --文件environment.yml --name base
    -名称:      - 名称：皮棉片8
      运行：|
        conda安装flake8
        # 如果存在 Python 语法错误或未定义的名称，则停止构建
        片8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero 将所有错误视为警告。GitHub 编辑器的宽度为 127 个字符
        片8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    -姓名：Test with pytest
      运行：|
        conda安装pytest
        py测试
